In [1]:

# #! echo $PWD
! pip install ../utility_functions/
# #!pip install ~/fwiViz/utility_functions/

Processing /home/jovyan/fwiVis/utility_functions
  Preparing metadata (setup.py) ... done
Requirement already satisfied: s3fs in /srv/conda/envs/notebook/lib/python3.12/site-packages (from fwiVis==0.1) (2024.10.0)
Requirement already satisfied: numpy in /srv/conda/envs/notebook/lib/python3.12/site-packages (from fwiVis==0.1) (2.0.2)
Requirement already satisfied: pandas in /srv/conda/envs/notebook/lib/python3.12/site-packages (from fwiVis==0.1) (2.2.3)
Requirement already satisfied: geopandas in /srv/conda/envs/notebook/lib/python3.12/site-packages (from fwiVis==0.1) (1.0.1)
Requirement already satisfied: matplotlib in /srv/conda/envs/notebook/lib/python3.12/site-packages (from fwiVis==0.1) (3.9.2)
Requirement already satisfied: xarray in /srv/conda/envs/notebook/lib/python3.12/site-packages (from fwiVis==0.1) (2024.10.0)
Requirement already satisfied: rioxarray in /srv/conda/envs/notebook/lib/python3.12/site-packages (from fwiVis==0.1) (0.17.0)
Requirement already satisfied: rasterio in /srv/conda/envs/notebook/lib/python3.12/site-packages (from fwiVis==0.1) (1.4.2)
Requirement already satisfied: geocube in /srv/conda/envs/notebook/lib/python3.12/site-packages (from fwiVis==0.1) (0.7.0)
Requirement already satisfied: shapely in /srv/conda/envs/notebook/lib/python3.12/site-packages (from fwiVis==0.1) (2.0.6)
Requirement already satisfied: folium in /srv/conda/envs/notebook/lib/python3.12/site-packages (from fwiVis==0.1) (0.18.0)
Requirement already satisfied: branca>=0.6.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from folium->fwiVis==0.1) (0.7.2)
Requirement already satisfied: jinja2>=2.9 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from folium->fwiVis==0.1) (3.1.4)
Requirement already satisfied: requests in /srv/conda/envs/notebook/lib/python3.12/site-packages (from folium->fwiVis==0.1) (2.32.3)
Requirement already satisfied: xyzservices in /srv/conda/envs/notebook/lib/python3.12/site-packages (from folium->fwiVis==0.1) (2024.9.0)
Requirement already satisfied: appdirs in /srv/conda/envs/notebook/lib/python3.12/site-packages (from geocube->fwiVis==0.1) (1.4.4)
Requirement already satisfied: click>=6.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from geocube->fwiVis==0.1) (8.1.7)
Requirement already satisfied: odc-geo in /srv/conda/envs/notebook/lib/python3.12/site-packages (from geocube->fwiVis==0.1) (0.4.8)
Requirement already satisfied: scipy in /srv/conda/envs/notebook/lib/python3.12/site-packages (from geocube->fwiVis==0.1) (1.14.1)
Requirement already satisfied: pyproj>=2 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from geocube->fwiVis==0.1) (3.7.0)
Requirement already satisfied: pyogrio>=0.7.2 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from geopandas->fwiVis==0.1) (0.10.0)
Requirement already satisfied: packaging in /srv/conda/envs/notebook/lib/python3.12/site-packages (from geopandas->fwiVis==0.1) (24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pandas->fwiVis==0.1) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pandas->fwiVis==0.1) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pandas->fwiVis==0.1) (2024.2)
Requirement already satisfied: affine in /srv/conda/envs/notebook/lib/python3.12/site-packages (from rasterio->fwiVis==0.1) (2.4.0)
Requirement already satisfied: attrs in /srv/conda/envs/notebook/lib/python3.12/site-packages (from rasterio->fwiVis==0.1) (24.2.0)
Requirement already satisfied: certifi in /srv/conda/envs/notebook/lib/python3.12/site-packages (from rasterio->fwiVis==0.1) (2024.12.14)
Requirement already satisfied: cligj>=0.5 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from rasterio->fwiVis==0.1) (0.7.2)
Requirement already satisfied: click-plugins in /srv/conda/envs/notebook/lib/python3.12/site-packages (from rasterio->fwiVis==0.1) (1.1.1)
Requirement already satisfied: pyparsing in /srv/conda/envs/notebook/lib/python3.12/site-packages (from rasterio->fwiVis==0.1) (3.2.0)
Requirement already satisfied: contourpy>=1.0.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from matplotlib->fwiVis==0.1) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from matplotlib->fwiVis==0.1) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from matplotlib->fwiVis==0.1) (4.54.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from matplotlib->fwiVis==0.1) (1.4.7)
Requirement already satisfied: pillow>=8 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from matplotlib->fwiVis==0.1) (11.0.0)
Requirement already satisfied: aiobotocore<3.0.0,>=2.5.4 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from s3fs->fwiVis==0.1) (2.15.2)
Requirement already satisfied: fsspec==2024.10.0.* in /srv/conda/envs/notebook/lib/python3.12/site-packages (from s3fs->fwiVis==0.1) (2024.10.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from s3fs->fwiVis==0.1) (3.10.10)
Requirement already satisfied: botocore<1.35.37,>=1.35.16 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs->fwiVis==0.1) (1.35.36)
Requirement already satisfied: wrapt<2.0.0,>=1.10.10 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs->fwiVis==0.1) (1.16.0)
Requirement already satisfied: aioitertools<1.0.0,>=0.5.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs->fwiVis==0.1) (0.12.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs->fwiVis==0.1) (2.4.3)
Requirement already satisfied: aiosignal>=1.1.2 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs->fwiVis==0.1) (1.3.1)
Requirement already satisfied: frozenlist>=1.1.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs->fwiVis==0.1) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs->fwiVis==0.1) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs->fwiVis==0.1) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from jinja2>=2.9->folium->fwiVis==0.1) (3.0.2)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->fwiVis==0.1) (1.16.0)
Requirement already satisfied: cachetools in /srv/conda/envs/notebook/lib/python3.12/site-packages (from odc-geo->geocube->fwiVis==0.1) (5.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from requests->folium->fwiVis==0.1) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from requests->folium->fwiVis==0.1) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from requests->folium->fwiVis==0.1) (1.26.19)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from botocore<1.35.37,>=1.35.16->aiobotocore<3.0.0,>=2.5.4->s3fs->fwiVis==0.1) (1.0.1)
Requirement already satisfied: propcache>=0.2.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from yarl<2.0,>=1.12.0->aiohttp!=4.0.0a0,!=4.0.0a1->s3fs->fwiVis==0.1) (0.2.0)
Building wheels for collected packages: fwiVis
  Building wheel for fwiVis (setup.py) ... done
  Created wheel for fwiVis: filename=fwiVis-0.1-py3-none-any.whl size=17985 sha256=a941d6460d322aa045fcc980e0b661a5ec88e01255da00aa67574d0cf15171be
  Stored in directory: /tmp/pip-ephem-wheel-cache-rg1htvuo/wheels/79/0f/3d/08c18473dd7e0fb915900e6b4f13b81f1fa84371f9bf24d864
Successfully built fwiVis
Installing collected packages: fwiVis
Successfully installed fwiVis-0.1

In [3]:
import fwiVis.fwiVis as fv
import s3fs
s3 = s3fs.S3FileSystem(anon=False)
from math import cos, asin, sqrt
import re

import numpy as np
import geopandas as gpd
import pandas as pd
from matplotlib import pyplot as plt
import os
import rioxarray as rio
import xarray as xr
import rasterio
import glob
from shapely.errors import ShapelyDeprecationWarning
from shapely.geometry import Point
import warnings
import folium
import datetime
import time
from folium import plugins
warnings.filterwarnings("ignore", category=ShapelyDeprecationWarning) 
warnings.filterwarnings("ignore", category=ShapelyDeprecationWarning) 
#import contextily as cx
from shapely.geometry import box
import sys
from datetime import datetime, timedelta
from itertools import chain
from bs4 import BeautifulSoup # I mamba installed bs4
import requests

from datetime import date

In [3]:



# def make_df_of_fires(year = "2023", path_region = "Quebec_PostHoc", custom_path = "/home/jovyan/fireatlast_nrt/fireatlas/data/FEDSoutput-v3/"):

#     diroutdata = custom_path
#     spath = os.path.join(diroutdata, path_region, str(year), "Largefire")
#     fnms = [f for f in os.listdir(spath)]
#     print(fnms)
#     #fnms = fnms.sort()
#     tmp_ids = pd.DataFrame(fnms, columns=["ids"])
#     #tmp_ids = tmp_ids[~tmp_ids.ids.str.contains(".")]
#     print(tmp_ids)
#     tmp_ids = tmp_ids.ids.unique()
#     print(f'{len(tmp_ids)} unique ID found')

#     print("Reading in IDS")
#     ### reading in the ids
#     fires = pd.DataFrame()
#     for n,i in enumerate(tmp_ids, start = 0):
#         try:
#             foo = fv.load_large_fire(i, year = year, path_region= path_region, layer = "perimeter",  s3_path = False, custom_path = custom_path)
#             foo["fireID"] = str(i)
#         except Exception as e:
#             print("Error at ID: ",i)
#             print(e)
#             continue
#         ## Extract the period between 
#         fires = pd.concat([fires, foo])
#     return (fires)
#         #print(fires)
#             #fr_pd = pd.DataFrame(fires, columns=["lat", "lon", "farea", "data_source"])
#         #fires.to_csv("/projects/old_shared/fire_weather_vis/Lightning_analysis/fwi_timeline_merge/"+"20_days_fire_stats_only_718270-99999_" +min_t + max_t + path_region + FWI_source + str(date.today().strftime("%Y%m%d"))+  ".csv")

In [4]:
# fires = make_df_of_fires()

In [4]:
## but wait, maybe Julia made a function for combined lf anyway


lf = gpd.read_file("/home/jovyan/fireatlast_nrt/fireatlas/data/FEDSoutput-v3/Quebec_V3/2023/CombinedLargefire/20230915PM/lf_perimeter.fgb")

In [5]:
len(lf.fireID.unique())

204

In [6]:
def get_largest_perimeter(df):
    fireID = df.fireID
    df = df[(np.round(df.farea, 4) == np.round(df.farea.max(), 4)) & (df.t == df.t.max())]
    if(len(df) == 0):
        print(f"Warning! dropping ID {fireID} because max t didn't match max farea.")
    return(df)

In [8]:
#new_lf = lf.groupby("fireID").apply(get_largest_perimeter,  include_groups = True )

In [9]:
#new_lf.explore()

In [10]:
# print(len(lf.fireID.unique()))
# len(new_lf.fireID.unique())

In [11]:
# new_lf = new_lf.to_crs("4326")
# new_lf["lat_centroid"] = new_lf.geometry.centroid.y
# new_lf["lon_centroid"] = new_lf.geometry.centroid.x

# new_lf.columns

In [12]:
# new_lf.fireID = new_lf.fireID.astype("int")
# new_lf.mergeid = new_lf.mergeid.astype("int")

In [13]:
lf.fireID = lf.fireID.astype("int")
lf.mergeid = lf.mergeid.astype("int")

In [14]:
# import datetime
# now = date.today()
# new_lf.fireID = new_lf.fireID.astype('int')
# new_lf.mergeid = new_lf.mergeid.astype('int')
# new_lf.lon_centroid = new_lf.centroid.x
# new_lf.lat_centroid = new_lf.centroid.y
# new_lf = new_lf.drop(columns = "geometry")

# new_lf.to_csv("~/fwiVis/notebooks/data/Quebec_v3_last_perimeters_as_of_" + str(now.year)+str(now.month)+str(now.day)+".csv")

In [15]:
# print(len(lf[~lf.fireID.isin(new_lf.fireID.unique())].fireID.unique()))
# weird_ids = lf[~lf.fireID.isin(new_lf.fireID.unique())].fireID.unique()
# print(weird_ids)

In [45]:
def listFD(url, ext=''):
    page = requests.get(url).text
    #print(page)
    soup = BeautifulSoup(page, 'html.parser')
    return [url + '/' + node.get('href') for node in soup.find_all('a') if node.get('href').endswith(ext)]

## https://portal.nccs.nasa.gov/datashare/GlobalFWI/ForecastFWIEXPERIMENTAL/QuebecAllFires.Radius.25.km.247.biggestFires/
# https://portal.nccs.nasa.gov/datashare/GlobalFWI/ForecastFWIEXPERIMENTAL/QuebecAllFires.Radius.25.km.216.biggestFires/GEOS-5/GEOS-5.IMERGEARLY/chicletDataNoSmoothing/
# https://portal.nccs.nasa.gov/datashare/GlobalFWI/ForecastFWIEXPERIMENTAL/QuebecFEDSv3.Radius.50.km.176.biggestFires/
# 'https://portal.nccs.nasa.gov/datashare/GlobalFWI/ForecastFWIEXPERIMENTAL/QuebecAllFires.Radius.25.km.247.biggestFires/GEOS-5/GEOS-5.IMERGEARLY/chicletDataNoSmoothing/
# 'https://portal.nccs.nasa.gov/datashare/GlobalFWI/ForecastFWIEXPERIMENTAL/QuebecFEDSv3.Radius.50.km.176.biggestFires/GEOS-5/GEOS-5.IMERGEARLY/MAX/chicletDataNoSmoothing/'
def get_nccs_url(pattern, url = 'https://portal.nccs.nasa.gov/datashare/GlobalFWI/ForecastFWIEXPERIMENTAL/QuebecFEDSv3.Radius.50.km.204.biggestFires/GEOS-5/GEOS-5.IMERGEARLY/MAX/chicletDataNoSmoothing/', ext = 'csv', pattern2 = "FWI.raw"):    

#url = 'https://portal.nccs.nasa.gov/datashare/GlobalFWI/ForecastFWIEXPERIMENTAL/QuebecAllFires.Radius.25.km.216.biggestFires/GEOS-5/GEOS-5.IMERGEARLY/chicletDataNoSmoothing/'
#ext = 'csv'
    file_list = []
    for file in listFD(url, ext):
        file_list.append(file)

    try_pd = pd.DataFrame(file_list, columns= ["urls"])
    size = try_pd[try_pd.urls.str.contains(pattern)].urls.values.size
    if(pattern2 is not None):
        #print(f"Searching by second pattern {pattern2}")
        size = try_pd[(try_pd.urls.str.contains(pattern)) & (try_pd.urls.str.contains(pattern2))].urls.values.size
        print(size)
    if(size == 0):
        print("No matches found to pattern. Returning None.")
        return(None)
    if(size >= 2):
        print("Multiple matches found:")
        #print(try_pd[try_pd.urls.str.contains(pattern)].urls.values)
        print(try_pd[try_pd.urls.str.contains(pattern) & try_pd.urls.str.contains(pattern2)].urls.values)
        raise ValueError()
    url = try_pd[try_pd.urls.str.contains(pattern)].urls.values[0]
    if(pattern2 is not None):
        url = try_pd[try_pd.urls.str.contains(pattern) & try_pd.urls.str.contains(pattern2)].urls.values[0]
    return(url)

def get_gridded_fwi(fireID):
    
    # Get the URL for the file
    fireID = str(fireID)
    #pattern = "FWI." + fireID
    pattern = "\." + fireID + "\_Lat"
    url = get_nccs_url(pattern = pattern, pattern2 = pattern2)
    print(url)
    if(url is not None):
        
        # Get the DF
        grid_FWI = pd.read_csv(url)
        # Change names
        grid_FWI = grid_FWI.rename(columns={'INITDATE': 't', 
                                 "0":"FWI",
                                 "1":"FWI_lead_1",
                                 "2":"FWI_lead_2",
                                 "3":"FWI_lead_3",
                                 "4":"FWI_lead_4",
                                 "5":"FWI_lead_5",
                                 "6":"FWI_lead_6",
                                 "7":"FWI_lead_7",
                                 "8":"FWI_lead_8"
                                })
        # Change dates
        grid_FWI.t = grid_FWI.t.astype("datetime64[ns]").dt.strftime('%Y-%m-%d 12:00:00')

        # return
        return(grid_FWI)
    else:
        return(None)

# 'https://portal.nccs.nasa.gov/datashare/GlobalFWI/ForecastFWIEXPERIMENTAL/QuebecFEDSv3.Radius.50.km.204.biggestFires/GEOS-5/GEOS-5.IMERGEARLY/MEAN/chicletDataNoSmoothing/
def get_gridded_met(fireID, met_name = "FWI", pattern2 = "FWI.raw", url = 'https://portal.nccs.nasa.gov/datashare/GlobalFWI/ForecastFWIEXPERIMENTAL/QuebecFEDSv3.Radius.50.km.204.biggestFires/GEOS-5/GEOS-5.IMERGEARLY/MAX/chicletDataNoSmoothing/',  pattern3 = ""):
    
    # Get the URL for the file
    fireID = str(fireID)
    #pattern = "ISI." + fireID
    pattern = "\." + fireID + "\_Lat"
    url = get_nccs_url(pattern = pattern, pattern2 = pattern2, url = url)
    #print(url)
    if(url is not None):
        
        # Get the DF
        grid = pd.read_csv(url)
        # Change names
        grid = grid.rename(columns={'INITDATE': 't', 
                                 "GEOS-5.IMERGEARLY":f"GEOS-5.IMERGEARLY{pattern3}",
                                 "0":f"{met_name}",
                                 "1":f"{met_name}_lead_1",
                                 "2":f"{met_name}_lead_2",
                                 "3":f"{met_name}_lead_3",
                                 "4":f"{met_name}_lead_4",
                                 "5":f"{met_name}_lead_5",
                                 "6":f"{met_name}_lead_6",
                                 "7":f"{met_name}_lead_7",
                                 "8":f"{met_name}_lead_8"
                                })
        #print(grid)
        # Change dates
        grid.t = grid.t.astype("datetime64[ns]").dt.strftime('%Y-%m-%d 12:00:00')

        # return
        return(grid)
    else:
        print("Url is none.")
        print(url)
        return(None)

<>:44: SyntaxWarning: invalid escape sequence '\.'
<>:44: SyntaxWarning: invalid escape sequence '\_'
<>:77: SyntaxWarning: invalid escape sequence '\.'
<>:77: SyntaxWarning: invalid escape sequence '\_'
<>:44: SyntaxWarning: invalid escape sequence '\.'
<>:44: SyntaxWarning: invalid escape sequence '\_'
<>:77: SyntaxWarning: invalid escape sequence '\.'
<>:77: SyntaxWarning: invalid escape sequence '\_'
/tmp/ipykernel_397/2874259750.py:44: SyntaxWarning: invalid escape sequence '\.'
  pattern = "\." + fireID + "\_Lat"
/tmp/ipykernel_397/2874259750.py:44: SyntaxWarning: invalid escape sequence '\_'
  pattern = "\." + fireID + "\_Lat"
/tmp/ipykernel_397/2874259750.py:77: SyntaxWarning: invalid escape sequence '\.'
  pattern = "\." + fireID + "\_Lat"
/tmp/ipykernel_397/2874259750.py:77: SyntaxWarning: invalid escape sequence '\_'
  pattern = "\." + fireID + "\_Lat"

In [46]:
# lf.to_csv("~/fwiVis/notebooks/data/Quebec_v3_perimeters_as_of_" + str(now.year)+str(now.month)+str(now.day)+".csv")

In [47]:
smol = lf[lf.fireID == lf.fireID.iloc[0]]
fireID = smol.fireID.iloc[0]
fwi = get_gridded_met(str(fireID))

1

In [48]:
#fwi.merge(smol, on = ["t"], how = "outer").n_newpixels.unique()
fwi = get_gridded_met(str("226"))

1

In [49]:
def merge_gridded_FWI_data(df, FWI_subset_t = False, met_vars = ["FWI", "ISI", "BUI"], 
                           met_urls = ['https://portal.nccs.nasa.gov/datashare/GlobalFWI/ForecastFWIEXPERIMENTAL/QuebecFEDSv3MoreIndices.Radius.50.km.204.biggestFires/GEOS-5/GEOS-5.IMERGEARLY/MAX/chicletDataNoSmoothing/',
                                       'https://portal.nccs.nasa.gov/datashare/GlobalFWI/ForecastFWIEXPERIMENTAL/QuebecFEDSv3MoreIndices.Radius.50.km.204.biggestFires/GEOS-5/GEOS-5.IMERGEARLY/MAX/chicletDataNoSmoothing/', 
                                       'https://portal.nccs.nasa.gov/datashare/GlobalFWI/ForecastFWIEXPERIMENTAL/QuebecFEDSv3MoreIndices.Radius.50.km.204.biggestFires/GEOS-5/GEOS-5.IMERGEARLY/MAX/chicletDataNoSmoothing/' ],
                           met_pattern2 = ["FWI.raw", "ISI.raw", "BUI.raw"], met_pattern3 = ["", "_ISI", "_BUI"]):
    fireID = df.fireID.iloc[0]
    df.t = df.t.astype("datetime64[ns]")
    result_df = df.copy()  # Create a copy of the original dataframe
    
    for i, m in enumerate(met_vars):
        current_fwi = get_gridded_met(str(fireID), met_name = met_vars[i], 
                                    pattern2 = met_pattern2[i], url = met_urls[i], pattern3 = met_pattern3[i])
        #print(f'{met_pattern2[i]}')
        #print(f'{met_vars[i]}')
       # print(current_fwi[f'{met_vars[i]}'].iloc[203])
        #print(f'{met_vars[i]}')
        if(current_fwi is None):
            print(f"Warning:{met_vars[i]} in {fireID} was not extracted sucessfully.")
            print({met_urls[i]})
            return None
        else:
            current_fwi.t = current_fwi.t.astype("datetime64[ns]")
            current_fwi.loc[:, "fireID"] = fireID
            
            if(FWI_subset_t):
                current_fwi = current_fwi[current_fwi.t.astype("datetime64[ns]") >= result_df.t.astype("datetime64[ns]").min()]
                current_fwi = current_fwi[current_fwi.t.astype("datetime64[ns]") <= result_df.t.astype("datetime64[ns]").max()]
        
            result_df = result_df.merge(current_fwi, on = ["fireID", "t"], how = "outer")
    
    return result_df

In [51]:
col_names = lf.columns

lf.fireID = lf.fireID.astype("int")
lf.fireID = lf.fireID.astype("str")


merged_lf = lf.groupby("fireID")[col_names].apply(merge_gridded_FWI_data).reset_index(drop=True) #include_groups=True ## This rearranges the columns so that fireID isn't first. 
#test = smol.groupby("fireID")[col_names].apply(merge_gridded_FWI_data).reset_index() #include_groups=True
merged_lf 

#merged_lf.BUI.dropna() == merged_lf.FWI.dropna()

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1

,mergeid,ftype,n_pixels,n_newpixels,farea,fperim,flinelen,duration,pixden,meanFRP,...,GEOS-5.IMERGEARLY_BUI,BUI,BUI_lead_1,BUI_lead_2,BUI_lead_3,BUI_lead_4,BUI_lead_5,BUI_lead_6,BUI_lead_7,BUI_lead_8
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157691,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157693,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157694,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157695,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
# col_names = lf.columns

# lf.fireID = lf.fireID.astype("int")
# lf.fireID = lf.fireID.astype("str")

# tmp = lf[lf.fireID == '226']
# merged_lf = merge_gridded_FWI_data(tmp) #include_groups=True ## This rearranges the columns so that fireID isn't first. 
# #test = smol.groupby("fireID")[col_names].apply(merge_gridded_FWI_data).reset_index() #include_groups=True
# merged_lf 

# #merged_lf.BUI.dropna() == merged_lf.FWI.dropna()

/srv/conda/envs/notebook/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

1
1
1

,mergeid,ftype,n_pixels,n_newpixels,farea,fperim,flinelen,duration,pixden,meanFRP,...,GEOS-5.IMERGEARLY_BUI,BUI,BUI_lead_1,BUI_lead_2,BUI_lead_3,BUI_lead_4,BUI_lead_5,BUI_lead_6,BUI_lead_7,BUI_lead_8
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
832,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
835,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
836,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# col_names = lf.columns

# lf.fireID = lf.fireID.astype("int")
# lf.fireID = lf.fireID.astype("str")


# merged_lf = lf.groupby("fireID")[col_names].apply(merge_gridded_FWI_data).reset_index(drop=True) #include_groups=True ## This rearranges the columns so that fireID isn't first. 
# #test = smol.groupby("fireID")[col_names].apply(merge_gridded_FWI_data).reset_index() #include_groups=True
# merged_lf

In [52]:
import datetime
now = date.today()

merged_lf.to_csv("~/fwiVis/notebooks/data/Quebec_v3_full_data_perimeters"+ "MAX_fwi_with_ISI_and_BUI" + "ful_timeseries_" + str(now.year)+str(now.month)+str(now.day)+".csv")

In [24]:
merged_lf['GEOS-5.IMERGEARLY'].unique()

array([           nan, 4.18151855e+00, 4.58382750e+00, 1.32272422e-01,
       1.00814700e+00, 1.14874291e+00, 4.36931992e+00, 5.03310299e+00,
       6.73083115e+00, 8.09321594e+00, 8.35452652e+00, 9.43735027e+00,
       9.98350143e+00, 1.46826935e+01, 7.72254133e+00, 6.36088896e+00,
       8.49648571e+00, 1.04301088e-01, 3.31574082e+00, 4.20471668e+00,
       4.42501259e+00, 8.98884535e-01, 9.13744390e-01, 3.42909050e+00,
       8.14196396e+00, 1.22817268e+01, 1.18143663e+01, 1.30960722e+01,
       1.67687263e+01, 1.76056156e+01, 1.15633783e+01, 1.06273909e+01,
       1.36381779e+01, 7.62161589e+00, 1.08729610e+01, 1.06922922e+01,
       1.26898403e+01, 9.99564457e+00, 1.23744688e+01, 7.51217842e+00,
       7.72508812e+00, 5.04784212e-02, 3.30954354e-05, 1.39104620e-01,
       2.45117068e-01, 6.40013397e-01, 2.54480314e+00, 6.01722145e+00,
       9.29628658e+00, 1.02057085e+01, 1.36652498e+01, 1.43177271e+01,
       1.40790596e+01, 1.20598087e+01, 3.12030888e+00, 6.80023015e-01,
       1.52374387e-01, 8.03379655e-01, 5.07417011e+00, 6.15048838e+00,
       6.08707523e+00, 7.43014765e+00, 9.81302357e+00, 1.17440844e+01,
       1.36360502e+01, 3.56776857e+00, 6.80331802e+00, 3.40573573e+00,
       7.13889122e+00, 1.20447721e+01, 7.77278066e-01, 2.13302898e+00,
       4.34047699e+00, 8.18212605e+00, 8.22071934e+00, 6.31714487e+00,
       4.37588835e+00, 5.53342199e+00, 6.24491310e+00, 8.39578092e-01,
       3.97782779e+00, 5.87222719e+00, 1.74155831e+00, 3.25092149e+00,
       6.19517326e+00, 3.97623706e+00, 7.16305065e+00, 4.89845037e+00,
       6.92612076e+00, 7.41958141e+00, 8.19980145e+00, 9.45273876e+00,
       1.00694828e+01, 1.43428802e+00, 3.05343533e+00, 5.68868637e+00,
       8.37069321e+00, 1.43503630e+00, 4.01597738e+00, 7.69072866e+00,
       2.43129969e+00, 3.35514927e+00, 1.01390883e-01, 8.40827286e-01,
       2.28130007e+00, 4.39217186e+00, 8.19425297e+00, 1.84254691e-01,
       8.13792288e-01, 3.56157589e+00, 4.00969934e+00, 4.17932606e+00,
       6.30851889e+00, 4.54453826e-01, 7.30071008e-01, 6.35811925e-01,
       2.53156972e+00, 4.19664383e+00, 7.90859795e+00, 2.65860144e-04,
       3.10527772e-01, 8.28954697e-01, 6.15899849e+00, 7.00487614e+00,
       6.56477451e+00, 6.71283484e+00, 1.06037254e+01, 3.15478116e-01,
       2.42654383e-02, 4.64959919e-01, 8.64488304e-01, 1.93527043e+00,
       1.47575700e+00, 2.45934408e-02, 1.79740265e-01, 6.16776884e-01,
       2.43681717e+00, 2.95105362e+00, 3.23956537e+00, 5.14296865e+00,
       5.61648035e+00, 6.63411188e+00, 6.77526522e+00, 6.72459793e+00,
       7.28264856e+00, 8.05046463e+00, 9.37869167e+00, 9.88852501e+00,
       1.04922085e+01, 1.17785339e+01, 1.25781565e+01, 9.54066563e+00,
       6.98876429e+00, 4.55227673e-01, 3.16898227e+00, 8.27467251e+00,
       4.54963833e-01, 8.85624170e-01, 1.55315006e+00, 4.04785693e-01,
       2.01810908e+00, 3.29854703e+00, 3.35463619e+00, 3.62127066e+00,
       5.05722141e+00, 5.79254236e-04, 7.33567809e-04, 1.30294546e-01,
       2.49302000e-01, 1.71103235e-03, 1.07720763e-04, 6.20807114e-04,
       8.83485097e-03, 2.59597898e-01, 6.65966840e-03, 1.74138665e+00,
       4.20475340e+00, 3.63388610e+00, 4.53723621e+00, 4.80644083e+00,
       9.53438520e-01, 2.47996879e+00, 4.14881659e+00, 4.48420191e+00,
       1.99390960e+00, 1.52583170e+00, 2.60015798e+00, 4.02740955e+00,
       6.12772179e+00, 5.98201394e-01, 3.12817907e+00, 8.94812012e+00,
       1.51675951e+00, 2.27117634e+00, 2.93448180e-01, 2.50012565e+00,
       2.21195674e+00, 1.36651248e-02, 7.12800086e-01, 1.11439243e-01,
       6.29607677e-01, 2.61498547e+00, 5.74688435e+00, 9.67202568e+00,
       1.17454863e+01, 8.87290287e+00, 1.20876131e+01, 1.10109501e+01,
       7.95313978e+00, 8.00499797e-01, 1.14325750e+00, 5.77490282e+00,
       5.80990362e+00, 8.65642166e+00, 9.56621933e+00, 1.27014961e+01,
       1.55563426e+00, 3.61353111e+00, 7.05960798e+00, 1.08604901e-01,
       4.75559324e-01, 5.21517932e-01, 2.54025674e+00, 4.68892574e+00,
       5.21187973e+00, 2.59320879e+00, 4.04318757e-02, 6.83174372e-01,
       2.08892703e+00, 2.71955132e+00, 4.95589924e+00, 8.91415000e-01,
       1.27447918e-01, 7.81285703e-01, 3.78831410e+00, 8.80851650e+00,
       1.27812207e+00, 3.85267806e+00, 1.82095170e-01, 5.38041353e-01,
       3.73530030e+00, 4.26507139e+00, 6.48023129e-01, 1.92078733e+00,
       4.07588196e+00, 8.49861526e+00, 9.98801327e+00, 7.57633448e+00,
       7.70856094e+00, 9.47215080e+00, 7.75057411e+00, 9.05870914e+00,
       1.25359344e+01, 1.14997358e+01, 1.08738165e+01, 1.05609083e+01,
       7.08065271e+00, 3.57316470e+00, 1.01442671e+01, 1.34052229e+01,
       1.66592846e+01, 1.82109890e+01, 1.34278326e+01, 1.15905256e+01,
       1.43390331e+01, 1.78054829e+01, 1.93637791e+01, 2.06099110e+01,
       1.86005859e+01, 1.94789963e+01, 2.02377968e+01, 1.93319187e+01,
       3.59676933e+00, 6.87826490e+00, 3.14006233e+00, 4.08803988e+00,
       7.13708258e+00, 1.14075136e+01, 1.26981945e+01, 1.48253012e+01,
       1.31258955e+01, 9.28453356e-02, 1.57255769e+00, 3.57684684e+00,
       7.76948452e+00, 1.06838446e+01, 1.28373423e+01, 1.61911850e+01,
       8.01113701e+00, 9.06950283e+00, 1.21106319e+01, 1.17548062e-02,
       3.52378905e-01, 1.73463285e+00, 8.13387096e-01, 3.37797856e+00,
       4.34648544e-01, 1.95631015e+00, 5.55823755e+00, 8.13894939e+00,
       6.38438368e+00, 4.03659455e-02, 5.17687261e-01, 3.54789108e-01,
       7.45586693e-01, 3.67023206e+00, 5.94615507e+00, 5.09169960e+00,
       6.47597837e+00, 8.11475563e+00, 1.05437374e+01, 1.15225277e+01,
       1.21267586e+01, 1.27107286e+01, 1.32587309e+01, 1.81860495e+00,
       2.70168328e+00, 5.29906511e-01, 1.26329458e+00, 1.92455399e+00,
       8.31345379e-01, 3.75470448e+00, 6.46962690e+00, 7.87512398e+00,
       1.17175617e+01, 1.12739162e+01, 6.38772440e+00, 9.08195114e+00,
       9.91127872e+00, 1.05357084e+01, 1.05300140e+01, 1.60844669e-01,
       8.42065513e-01, 2.97599912e+00, 4.03632498e+00, 4.05006933e+00,
       5.49616861e+00, 6.11677599e+00, 6.84792137e+00, 6.47340202e+00])

In [25]:
merged_lf[merged_lf.fireID == '1003'].n_pixels.unique()

array([], dtype=float64)

In [26]:
merged_lf.to_csv("~/fwiVis/notebooks/data/Quebec_v3_full_data_perimeters"+ "MAX_fwi_" + "ful_timeseries_" + str(now.year)+str(now.month)+str(now.day)+".csv")

In [27]:
test = pd.read_csv("~/fwiVis/notebooks/data/Quebec_v3_full_data_perimeters"+ "MAX_fwi_" + "ful_timeseries_" + str(now.year)+str(now.month)+str(now.day)+".csv")

In [28]:
test['GEOS-5.IMERGEARLY'].unique()

array([           nan, 4.18151855e+00, 4.58382750e+00, 1.32272422e-01,
       1.00814700e+00, 1.14874291e+00, 4.36931992e+00, 5.03310299e+00,
       6.73083115e+00, 8.09321594e+00, 8.35452652e+00, 9.43735027e+00,
       9.98350143e+00, 1.46826935e+01, 7.72254133e+00, 6.36088896e+00,
       8.49648571e+00, 1.04301088e-01, 3.31574082e+00, 4.20471668e+00,
       4.42501259e+00, 8.98884535e-01, 9.13744390e-01, 3.42909050e+00,
       8.14196396e+00, 1.22817268e+01, 1.18143663e+01, 1.30960722e+01,
       1.67687263e+01, 1.76056156e+01, 1.15633783e+01, 1.06273909e+01,
       1.36381779e+01, 7.62161589e+00, 1.08729610e+01, 1.06922922e+01,
       1.26898403e+01, 9.99564457e+00, 1.23744688e+01, 7.51217842e+00,
       7.72508812e+00, 5.04784212e-02, 3.30954354e-05, 1.39104620e-01,
       2.45117068e-01, 6.40013397e-01, 2.54480314e+00, 6.01722145e+00,
       9.29628658e+00, 1.02057085e+01, 1.36652498e+01, 1.43177271e+01,
       1.40790596e+01, 1.20598087e+01, 3.12030888e+00, 6.80023015e-01,
       1.52374387e-01, 8.03379655e-01, 5.07417011e+00, 6.15048838e+00,
       6.08707523e+00, 7.43014765e+00, 9.81302357e+00, 1.17440844e+01,
       1.36360502e+01, 3.56776857e+00, 6.80331802e+00, 3.40573573e+00,
       7.13889122e+00, 1.20447721e+01, 7.77278066e-01, 2.13302898e+00,
       4.34047699e+00, 8.18212605e+00, 8.22071934e+00, 6.31714487e+00,
       4.37588835e+00, 5.53342199e+00, 6.24491310e+00, 8.39578092e-01,
       3.97782779e+00, 5.87222719e+00, 1.74155831e+00, 3.25092149e+00,
       6.19517326e+00, 3.97623706e+00, 7.16305065e+00, 4.89845037e+00,
       6.92612076e+00, 7.41958141e+00, 8.19980145e+00, 9.45273876e+00,
       1.00694828e+01, 1.43428802e+00, 3.05343533e+00, 5.68868637e+00,
       8.37069321e+00, 1.43503630e+00, 4.01597738e+00, 7.69072866e+00,
       2.43129969e+00, 3.35514927e+00, 1.01390883e-01, 8.40827286e-01,
       2.28130007e+00, 4.39217186e+00, 8.19425297e+00, 1.84254691e-01,
       8.13792288e-01, 3.56157589e+00, 4.00969934e+00, 4.17932606e+00,
       6.30851889e+00, 4.54453826e-01, 7.30071008e-01, 6.35811925e-01,
       2.53156972e+00, 4.19664383e+00, 7.90859795e+00, 2.65860144e-04,
       3.10527772e-01, 8.28954697e-01, 6.15899849e+00, 7.00487614e+00,
       6.56477451e+00, 6.71283484e+00, 1.06037254e+01, 3.15478116e-01,
       2.42654383e-02, 4.64959919e-01, 8.64488304e-01, 1.93527043e+00,
       1.47575700e+00, 2.45934408e-02, 1.79740265e-01, 6.16776884e-01,
       2.43681717e+00, 2.95105362e+00, 3.23956537e+00, 5.14296865e+00,
       5.61648035e+00, 6.63411188e+00, 6.77526522e+00, 6.72459793e+00,
       7.28264856e+00, 8.05046463e+00, 9.37869167e+00, 9.88852501e+00,
       1.04922085e+01, 1.17785339e+01, 1.25781565e+01, 9.54066563e+00,
       6.98876429e+00, 4.55227673e-01, 3.16898227e+00, 8.27467251e+00,
       4.54963833e-01, 8.85624170e-01, 1.55315006e+00, 4.04785693e-01,
       2.01810908e+00, 3.29854703e+00, 3.35463619e+00, 3.62127066e+00,
       5.05722141e+00, 5.79254236e-04, 7.33567809e-04, 1.30294546e-01,
       2.49302000e-01, 1.71103235e-03, 1.07720763e-04, 6.20807114e-04,
       8.83485097e-03, 2.59597898e-01, 6.65966840e-03, 1.74138665e+00,
       4.20475340e+00, 3.63388610e+00, 4.53723621e+00, 4.80644083e+00,
       9.53438520e-01, 2.47996879e+00, 4.14881659e+00, 4.48420191e+00,
       1.99390960e+00, 1.52583170e+00, 2.60015798e+00, 4.02740955e+00,
       6.12772179e+00, 5.98201394e-01, 3.12817907e+00, 8.94812012e+00,
       1.51675951e+00, 2.27117634e+00, 2.93448180e-01, 2.50012565e+00,
       2.21195674e+00, 1.36651248e-02, 7.12800086e-01, 1.11439243e-01,
       6.29607677e-01, 2.61498547e+00, 5.74688435e+00, 9.67202568e+00,
       1.17454863e+01, 8.87290287e+00, 1.20876131e+01, 1.10109501e+01,
       7.95313978e+00, 8.00499797e-01, 1.14325750e+00, 5.77490282e+00,
       5.80990362e+00, 8.65642166e+00, 9.56621933e+00, 1.27014961e+01,
       1.55563426e+00, 3.61353111e+00, 7.05960798e+00, 1.08604901e-01,
       4.75559324e-01, 5.21517932e-01, 2.54025674e+00, 4.68892574e+00,
       5.21187973e+00, 2.59320879e+00, 4.04318757e-02, 6.83174372e-01,
       2.08892703e+00, 2.71955132e+00, 4.95589924e+00, 8.91415000e-01,
       1.27447918e-01, 7.81285703e-01, 3.78831410e+00, 8.80851650e+00,
       1.27812207e+00, 3.85267806e+00, 1.82095170e-01, 5.38041353e-01,
       3.73530030e+00, 4.26507139e+00, 6.48023129e-01, 1.92078733e+00,
       4.07588196e+00, 8.49861526e+00, 9.98801327e+00, 7.57633448e+00,
       7.70856094e+00, 9.47215080e+00, 7.75057411e+00, 9.05870914e+00,
       1.25359344e+01, 1.14997358e+01, 1.08738165e+01, 1.05609083e+01,
       7.08065271e+00, 3.57316470e+00, 1.01442671e+01, 1.34052229e+01,
       1.66592846e+01, 1.82109890e+01, 1.34278326e+01, 1.15905256e+01,
       1.43390331e+01, 1.78054829e+01, 1.93637791e+01, 2.06099110e+01,
       1.86005859e+01, 1.94789963e+01, 2.02377968e+01, 1.93319187e+01,
       3.59676933e+00, 6.87826490e+00, 3.14006233e+00, 4.08803988e+00,
       7.13708258e+00, 1.14075136e+01, 1.26981945e+01, 1.48253012e+01,
       1.31258955e+01, 9.28453356e-02, 1.57255769e+00, 3.57684684e+00,
       7.76948452e+00, 1.06838446e+01, 1.28373423e+01, 1.61911850e+01,
       8.01113701e+00, 9.06950283e+00, 1.21106319e+01, 1.17548062e-02,
       3.52378905e-01, 1.73463285e+00, 8.13387096e-01, 3.37797856e+00,
       4.34648544e-01, 1.95631015e+00, 5.55823755e+00, 8.13894939e+00,
       6.38438368e+00, 4.03659455e-02, 5.17687261e-01, 3.54789108e-01,
       7.45586693e-01, 3.67023206e+00, 5.94615507e+00, 5.09169960e+00,
       6.47597837e+00, 8.11475563e+00, 1.05437374e+01, 1.15225277e+01,
       1.21267586e+01, 1.27107286e+01, 1.32587309e+01, 1.81860495e+00,
       2.70168328e+00, 5.29906511e-01, 1.26329458e+00, 1.92455399e+00,
       8.31345379e-01, 3.75470448e+00, 6.46962690e+00, 7.87512398e+00,
       1.17175617e+01, 1.12739162e+01, 6.38772440e+00, 9.08195114e+00,
       9.91127872e+00, 1.05357084e+01, 1.05300140e+01, 1.60844669e-01,
       8.42065513e-01, 2.97599912e+00, 4.03632498e+00, 4.05006933e+00,
       5.49616861e+00, 6.11677599e+00, 6.84792137e+00, 6.47340202e+00])

In [29]:
merged_lf[merged_lf.fireID == '512'].t.min()

NaT

In [30]:
merged_lf

,mergeid,ftype,n_pixels,n_newpixels,farea,fperim,flinelen,duration,pixden,meanFRP,...,GEOS-5.IMERGEARLY,BUI,BUI_lead_1,BUI_lead_2,BUI_lead_3,BUI_lead_4,BUI_lead_5,BUI_lead_6,BUI_lead_7,BUI_lead_8
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
merged_lf.columns

Index(['mergeid', 'ftype', 'n_pixels', 'n_newpixels', 'farea', 'fperim',
       'flinelen', 'duration', 'pixden', 'meanFRP', 't', 't_st', 't_ed',
       'fireID', 'isignition', 't_inactive', 'isactive', 'isdead',
       'mayreactivate', 'geom_counts', 'low_confidence_grouping', 'region',
       'primarykey', 'geometry', 'GEOS-5.IMERGEARLY_x', 'FWI', 'FWI_lead_1',
       'FWI_lead_2', 'FWI_lead_3', 'FWI_lead_4', 'FWI_lead_5', 'FWI_lead_6',
       'FWI_lead_7', 'FWI_lead_8', 'GEOS-5.IMERGEARLY_y', 'ISI', 'ISI_lead_1',
       'ISI_lead_2', 'ISI_lead_3', 'ISI_lead_4', 'ISI_lead_5', 'ISI_lead_6',
       'ISI_lead_7', 'ISI_lead_8', 'GEOS-5.IMERGEARLY', 'BUI', 'BUI_lead_1',
       'BUI_lead_2', 'BUI_lead_3', 'BUI_lead_4', 'BUI_lead_5', 'BUI_lead_6',
       'BUI_lead_7', 'BUI_lead_8'],
      dtype='object')